# Generated by Django 5.2 on 2025-04-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_remove_product_category_remove_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desc',
        ),
    ]
